### ISSUE TITLE
Live Demo

### ISSUE THREAD

**Issue by filiptronicek** [TropicSapling/ai-test#1]
I took a look at the repo and found it really interesting. I think there should be a live demo on the repo homepage - already hosted it on [Netlify](https://netlify.com) (to show how it could work, can be found [here](https://ai-test-triouc.netlify.app/)), but if you did it in the future, I would suggest using [Vercel](https://vercel.com/) for CD and also get a free *.now.sh subdomain. It would be nice to see something like this for people to try out.

Edit: noticed it's already hosted on [GH Pages](https://tropicsapling.github.io/ai-test/), would still be nice to have it in the README and the project metadata.

**Comment by TropicSapling** [comment]
Thank you for the suggestion. Apparently I had forgotten to link the live demo. I have now added it to both the README and the metadata :)
